name: CI Pipeline  # Name of the workflow

on:
  workflow_dispatch:   # Enables the workflow to be triggered manually
    inputs:
      environment:
        description: "Which environment to deploy"
        required: true
        default: "production"

jobs:
  build:
    runs-on: self-hosted    # Use self-hosted runner

    steps:
    #- name: Checkout code   # Step 1: Checkout the repository
    #  uses: actions/checkout@v3

    - name: Deploy a container
      run:
        cd docker
        echo "Building docker image"
        docker build -t git-docker-test
        echo "Starting a container"
        docker run -d -p 3000:9080
