name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy"
        required: true
        default: "dev"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        echo "Building docker image"
        cd docker
        docker build -t git-docker-test .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Deploy Docker container
      run: |
        echo "Starting Docker container"
        docker run -d -p 3000:80 git-docker-test

  test:
    runs-on: self-hosted
    needs: deploy
    steps:
    - name: Check if website is accessible
      run: |
        echo "Testing if the website is accessible"
        sleep 10  # Wait for a few seconds to ensure the container is up
        curl --fail http://localhost:3000
